import Coin from "../types/coin";

const list: Coin[] = [
  {
    code: "AAVE",
    name: "Aave",
    category: "utility token",
    famous: false,
  },
  {
    code: "ABFY",
    name: "Ambify",
    category: "cryptocurrencies",
    famous: false,
  },
  {
    code: "ACH",
    name: "Alchemy Pay",
    category: "utility token",
    famous: false,
  },
  {
    code: "ACMFT",
    name: "AC Milan",
    category: "utility token",
    famous: false,
  },
  {
    code: "ACORDO01",
    name: "None",
    category: "utility token",
    famous: false,
  },
  {
    code: "ADA",
    name: "Cardano",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "ADS",
    name: "Adshares",
    category: "utility token",
    famous: false,
  },
  {
    code: "AGIX",
    name: "SingularityNET",
    category: "utility token",
    famous: false,
  },
  {
    code: "AIOZ",
    name: "Aioz",
    category: "utility token",
    famous: false,
  },
  {
    code: "ALCX",
    name: "Alchemix",
    category: "utility token",
    famous: false,
  },
  {
    code: "ALGO",
    name: "Algorand",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "ALICE",
    name: "MyNeighborAlice",
    category: "utility token",
    famous: false,
  },
  {
    code: "ALLFT",
    name: "Alliance",
    category: "utility token",
    famous: false,
  },
  {
    code: "ALPHA",
    name: "Alpha Venture Dao",
    category: "utility token",
    famous: false,
  },
  {
    code: "AMFT",
    name: "Aston Martin Cognizant",
    category: "utility token",
    famous: false,
  },
  {
    code: "AMP",
    name: "Amp",
    category: "utility token",
    famous: false,
  },
  {
    code: "ANKR",
    name: "ANKR",
    category: "utility token",
    famous: false,
  },
  {
    code: "ANT",
    name: "Aragon",
    category: "utility token",
    famous: false,
  },
  {
    code: "APE",
    name: "ApeCoin",
    category: "utility token",
    famous: false,
  },
  {
    code: "API3",
    name: "API3",
    category: "utility token",
    famous: false,
  },
  {
    code: "APT",
    name: "Aptos",
    category: "cryptocurrencies",
    famous: false,
  },
  {
    code: "ARGFT",
    name: "Argentine Football Association",
    category: "utility token",
    famous: false,
  },
  {
    code: "ASRFT",
    name: "AS Roma",
    category: "utility token",
    famous: false,
  },
  {
    code: "ATLAS",
    name: "Star Atlas",
    category: "utility token",
    famous: false,
  },
  {
    code: "ATMFT",
    name: "Fan Token ATM",
    category: "utility token",
    famous: false,
  },
  {
    code: "ATOM",
    name: "Cosmos",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "AUDIO",
    name: "Audius",
    category: "utility token",
    famous: false,
  },
  {
    code: "AVAX",
    name: "Avalanche",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "AXS",
    name: "Axie Infinity",
    category: "utility token",
    famous: false,
  },
  {
    code: "BADGER",
    name: "Badger DAO",
    category: "utility token",
    famous: false,
  },
  {
    code: "BAL",
    name: "Balancer",
    category: "utility token",
    famous: false,
  },
  {
    code: "BAND",
    name: "Band Protocol",
    category: "utility token",
    famous: false,
  },
  {
    code: "BARFT",
    name: "FC Barcelona",
    category: "utility token",
    famous: false,
  },
  {
    code: "BAT",
    name: "Basic Attention token",
    category: "utility token",
    famous: false,
  },
  {
    code: "BCH",
    name: "Bitcoin Cash",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "BICO",
    name: "Biconomy",
    category: "utility token",
    famous: false,
  },
  {
    code: "BLZ",
    name: "Bluzelle",
    category: "utility token",
    famous: false,
  },
  {
    code: "BNT",
    name: "BANCOR",
    category: "utility token",
    famous: false,
  },
  {
    code: "BTB05",
    name: "BT Token Black 05",
    category: "utility token",
    famous: false,
  },
  {
    code: "BTB10",
    name: "BT Token Black 10",
    category: "utility token",
    famous: false,
  },
  {
    code: "BTC",
    name: "Bitcoin",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "BTRST",
    name: "Braintrust",
    category: "utility token",
    famous: false,
  },
  {
    code: "CAIFT",
    name: "Fan Token CAI",
    category: "utility token",
    famous: false,
  },
  {
    code: "CEEK",
    name: "CEEK VR",
    category: "utility token",
    famous: false,
  },
  {
    code: "CHZ",
    name: "Chiliz",
    category: "utility token",
    famous: false,
  },
  {
    code: "CITYFT",
    name: "Manchester City FC",
    category: "utility token",
    famous: false,
  },
  {
    code: "CLV",
    name: "Clover Finance",
    category: "utility token",
    famous: false,
  },
  {
    code: "COMP",
    name: "Compound",
    category: "utility token",
    famous: false,
  },
  {
    code: "CONS01",
    name: "Consorcio 01",
    category: "utility token",
    famous: false,
  },
  {
    code: "COTI",
    name: "COTI",
    category: "utility token",
    famous: false,
  },
  {
    code: "CRV",
    name: "Curve Dao Token",
    category: "utility token",
    famous: false,
  },
  {
    code: "CSCONS01",
    name: "Consorcio CS01",
    category: "utility token",
    famous: false,
  },
  {
    code: "CSCONS02",
    name: "Consorcio CS02",
    category: "utility token",
    famous: false,
  },
  {
    code: "CSCONS03",
    name: "Consórcio CS03",
    category: "utility token",
    famous: false,
  },
  {
    code: "CSCONS04",
    name: "Consorcio CS04",
    category: "utility token",
    famous: false,
  },
  {
    code: "CSCONS05",
    name: "Consorcio CS05",
    category: "utility token",
    famous: false,
  },
  {
    code: "CTSI",
    name: "Cartesi",
    category: "utility token",
    famous: false,
  },
  {
    code: "CVC",
    name: "Civic",
    category: "utility token",
    famous: false,
  },
  {
    code: "CVX",
    name: "Convex Finance",
    category: "utility token",
    famous: false,
  },
  {
    code: "DAI",
    name: "Dai",
    category: "utility token",
    famous: false,
  },
  {
    code: "DG",
    name: "Decentral Games",
    category: "utility token",
    famous: false,
  },
  {
    code: "DIA",
    name: "DIA",
    category: "utility token",
    famous: false,
  },
  {
    code: "DOGE",
    name: "Dogecoin",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "DOT",
    name: "Polkadot",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "DPI",
    name: "DeFi Pulse Index",
    category: "utility token",
    famous: false,
  },
  {
    code: "DYDX",
    name: "dYdX",
    category: "utility token",
    famous: false,
  },
  {
    code: "ENER01",
    name: "Token de Energia",
    category: "utility token",
    famous: false,
  },
  {
    code: "ENER02",
    name: "Energia 02",
    category: "utility token",
    famous: false,
  },
  {
    code: "ENER03",
    name: "Energia 03",
    category: "utility token",
    famous: false,
  },
  {
    code: "ENJ",
    name: "Enjin Coin",
    category: "utility token",
    famous: false,
  },
  {
    code: "ENS",
    name: "Ethereum Name Service",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "ERN",
    name: "Ethernity",
    category: "utility token",
    famous: false,
  },
  {
    code: "ETH",
    name: "Ethereum",
    category: "utility token",
    famous: false,
  },
  {
    code: "FARM",
    name: "Harvest Finance",
    category: "utility token",
    famous: false,
  },
  {
    code: "FET",
    name: "Fetch.ai",
    category: "utility token",
    famous: false,
  },
  {
    code: "FIL",
    name: "Filecoin",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "FLOKI",
    name: "Floki Inu",
    category: "utility token",
    famous: false,
  },
  {
    code: "FLOW",
    name: "Flow",
    category: "utility token",
    famous: false,
  },
  {
    code: "FTM",
    name: "None",
    category: "utility token",
    famous: false,
  },
  {
    code: "GALA",
    name: "Gala",
    category: "utility token",
    famous: false,
  },
  {
    code: "GALFT",
    name: "Galatasaray",
    category: "utility token",
    famous: false,
  },
  {
    code: "GALOFT",
    name: "Clube Atletico Mineiro",
    category: "utility token",
    famous: false,
  },
  {
    code: "GHST",
    name: "Aavegotchi",
    category: "utility token",
    famous: false,
  },
  {
    code: "GMT",
    name: "STEPN",
    category: "utility token",
    famous: false,
  },
  {
    code: "GNO",
    name: "Gnosis",
    category: "utility token",
    famous: false,
  },
  {
    code: "GODS",
    name: "Gods Unchained",
    category: "utility token",
    famous: false,
  },
  {
    code: "GRT",
    name: "The Graph",
    category: "utility token",
    famous: false,
  },
  {
    code: "GST",
    name: "Green Satoshi Token",
    category: "utility token",
    famous: false,
  },
  {
    code: "HIGH",
    name: "Highstreet",
    category: "utility token",
    famous: false,
  },
  {
    code: "HNT",
    name: "None",
    category: "utility token",
    famous: false,
  },
  {
    code: "HOT",
    name: "Holo",
    category: "utility token",
    famous: false,
  },
  {
    code: "ICP",
    name: "Internet Computer",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "ILV",
    name: "Illuvium",
    category: "utility token",
    famous: false,
  },
  {
    code: "IMOB01",
    name: "None",
    category: "utility token",
    famous: false,
  },
  {
    code: "IMOB02",
    name: "None",
    category: "utility token",
    famous: false,
  },
  {
    code: "IMX",
    name: "Immutable X",
    category: "utility token",
    famous: false,
  },
  {
    code: "INTERFT",
    name: "Inter Milan",
    category: "utility token",
    famous: false,
  },
  {
    code: "JASMY",
    name: "JasmyCoin",
    category: "utility token",
    famous: false,
  },
  {
    code: "JUVFT",
    name: "Juventus",
    category: "utility token",
    famous: false,
  },
  {
    code: "KEEP",
    name: "Keep Network",
    category: "utility token",
    famous: false,
  },
  {
    code: "KNC",
    name: "Kyber Network",
    category: "utility token",
    famous: false,
  },
  {
    code: "KP3R",
    name: "Keep3rV1",
    category: "utility token",
    famous: false,
  },
  {
    code: "KSM",
    name: "Kusama",
    category: "utility token",
    famous: false,
  },
  {
    code: "LDO",
    name: "Lido DAO Token",
    category: "utility token",
    famous: false,
  },
  {
    code: "LINK",
    name: "Chainlink",
    category: "utility token",
    famous: false,
  },
  {
    code: "LOOKS",
    name: "LooksRare",
    category: "utility token",
    famous: false,
  },
  {
    code: "LPT",
    name: "Livepeer",
    category: "utility token",
    famous: false,
  },
  {
    code: "LQTY",
    name: "Liquity",
    category: "utility token",
    famous: false,
  },
  {
    code: "LRC",
    name: "Loopring",
    category: "utility token",
    famous: false,
  },
  {
    code: "LTC",
    name: "Litecoin",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "MANA",
    name: "MANA (Decentraland)",
    category: "utility token",
    famous: false,
  },
  {
    code: "MATIC",
    name: "Polygon",
    category: "utility token",
    famous: false,
  },
  {
    code: "MBRL",
    name: "MBRL",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "MBSANTOS01",
    name: "Token da Vila",
    category: "utility token",
    famous: false,
  },
  {
    code: "MBTKN01",
    name: "MB TOKEN",
    category: "utility token",
    famous: false,
  },
  {
    code: "MBVASCO01",
    name: "Vasco Token",
    category: "utility token",
    famous: false,
  },
  {
    code: "MC",
    name: "Merit Circle",
    category: "utility token",
    famous: false,
  },
  {
    code: "MCO2",
    name: "Moss Carbon Credit",
    category: "utility token",
    famous: false,
  },
  {
    code: "MENGOFT",
    name: "Flamengo",
    category: "utility token",
    famous: false,
  },
  {
    code: "METIS",
    name: "MetisDAO",
    category: "utility token",
    famous: false,
  },
  {
    code: "MINA",
    name: "Mina",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "MIR",
    name: "Mirror Protocol",
    category: "utility token",
    famous: false,
  },
  {
    code: "MKR",
    name: "Maker",
    category: "utility token",
    famous: false,
  },
  {
    code: "MPL",
    name: "Maple",
    category: "utility token",
    famous: false,
  },
  {
    code: "MVI",
    name: "Metaverse Index",
    category: "utility token",
    famous: false,
  },
  {
    code: "NAVIFT",
    name: "Natus Vincere",
    category: "utility token",
    famous: false,
  },
  {
    code: "NODL",
    name: "Nodle",
    category: "cryptocurrencies",
    famous: false,
  },
  {
    code: "PAXG",
    name: "PAX Gold",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "PFLFT",
    name: "Professional Fighters League",
    category: "utility token",
    famous: false,
  },
  {
    code: "PORFT",
    name: "Portugal National Team FT",
    category: "utility token",
    famous: false,
  },
  {
    code: "POWR",
    name: "Power Ledger",
    category: "utility token",
    famous: false,
  },
  {
    code: "PSGFT",
    name: "Paris Saint-Germain",
    category: "utility token",
    famous: false,
  },
  {
    code: "SACI",
    name: "Sport Club Internacional",
    category: "utility token",
    famous: false,
  },
  {
    code: "SAND",
    name: "The Sandbox",
    category: "utility token",
    famous: false,
  },
  {
    code: "SAUBERFT",
    name: "Alfa Romeo Racing ORLEN",
    category: "utility token",
    famous: false,
  },
  {
    code: "SCCPFT",
    name: "Corinthians",
    category: "utility token",
    famous: false,
  },
  {
    code: "SHIB",
    name: "Shiba Inu",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "SKL",
    name: "SKALE Network",
    category: "utility token",
    famous: false,
  },
  {
    code: "SLP",
    name: "Smooth Love Potion",
    category: "utility token",
    famous: false,
  },
  {
    code: "SNX",
    name: "Synthetix",
    category: "utility token",
    famous: false,
  },
  {
    code: "SOL",
    name: "Solana",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "SPELL",
    name: "Spell Token",
    category: "utility token",
    famous: false,
  },
  {
    code: "SPFCFT",
    name: "SPFC",
    category: "utility token",
    famous: false,
  },
  {
    code: "STX",
    name: "Stacks",
    category: "cryptocurrencies",
    famous: false,
  },
  {
    code: "UFCFT",
    name: "UFC",
    category: "utility token",
    famous: false,
  },
  {
    code: "UMA",
    name: "Uma",
    category: "utility token",
    famous: false,
  },
  {
    code: "UNI",
    name: "Uniswap",
    category: "utility token",
    famous: false,
  },
  {
    code: "USDC",
    name: "USD Coin",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "USDP",
    name: "Pax Dollar",
    category: "utility token",
    famous: false,
  },
  {
    code: "VERDAO",
    name: "Sociedade Esportiva Palmeiras",
    category: "utility token",
    famous: false,
  },
  {
    code: "WLUNA",
    name: "Wrapped LUNA Token",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "XLM",
    name: "Stellar",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "XRP",
    name: "XRP",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "XTZ",
    name: "Tezos",
    category: "cryptocurrencies",
    famous: true,
  },
  {
    code: "FTBRL",
    name: "None",
    category: "utility token",
    famous: false,
  },
];

export default list;
